# Generated by Django 4.2.7 on 2024-05-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_blogpost_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='user',
        ),
        migrations.RemoveField(
            model_name='travelpreference',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Itinerary',
        ),
        migrations.DeleteModel(
            name='TravelPreference',
        ),
    ]
