# Generated by Django 4.2.7 on 2024-06-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_blogpost_remove_itinerary_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_paid_print_pdf',
            field=models.BooleanField(default=False),
        ),
    ]
