# Generated by Django 4.2.7 on 2024-05-30 12:15

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_itinerary_gmail_link_itinerary_image_itinerary_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='activities',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='content',
            field=markdownx.models.MarkdownxField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerary',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerary',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
