# Generated by Django 4.2.7 on 2024-05-30 15:15

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_gmail_link_itinerary_gmap_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='places_to_stay',
            new_name='covered_highlights',
        ),
        migrations.RenameField(
            model_name='itinerary',
            old_name='gmap_link',
            new_name='gmaps_link',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='content',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='details',
            field=markdownx.models.MarkdownxField(default=''),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='intro',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
