# Generated by Django 4.2.7 on 2024-06-02 12:53

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_culturalactivity_placetostay_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='covered_highlights',
            field=markdownx.models.MarkdownxField(default=''),
        ),
    ]
