# Generated by Django 4.2.7 on 2024-06-03 19:57

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_itinerary_covered_highlights'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'verbose_name': 'Itinerary', 'verbose_name_plural': 'Itineraries'},
        ),
        migrations.AddField(
            model_name='itinerary',
            name='covered_highlights_de',
            field=markdownx.models.MarkdownxField(default='', null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='covered_highlights_en',
            field=markdownx.models.MarkdownxField(default='', null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='details_de',
            field=markdownx.models.MarkdownxField(default='', null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='details_en',
            field=markdownx.models.MarkdownxField(default='', null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='intro_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='intro_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
