# Generated by Django 4.2.7 on 2024-06-04 15:25

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_itinerary_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='covered_highlights_de',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='details_de',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='intro_de',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='name_de',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='city',
            field=models.CharField(default='Cape Town', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerary',
            name='country',
            field=models.CharField(default='South Africa', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerary',
            name='covered_highlights_es',
            field=markdownx.models.MarkdownxField(default='', null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='covered_highlights_fr',
            field=markdownx.models.MarkdownxField(default='', null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='covered_highlights_pt',
            field=markdownx.models.MarkdownxField(default='', null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='covered_highlights_zh',
            field=markdownx.models.MarkdownxField(default='', null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='details_es',
            field=markdownx.models.MarkdownxField(default='', null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='details_fr',
            field=markdownx.models.MarkdownxField(default='', null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='details_pt',
            field=markdownx.models.MarkdownxField(default='', null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='details_zh',
            field=markdownx.models.MarkdownxField(default='', null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='intro_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='intro_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='intro_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='intro_zh',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='name_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='name_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='name_zh',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='travel_budget',
            field=models.CharField(choices=[('economy', 'Economy'), ('business', 'Business')], default='Economy', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerary',
            name='travel_mode',
            field=models.CharField(choices=[('solo', 'Solo'), ('couple', 'Couple'), ('family', 'Family'), ('other', 'Other')], default='Solo', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerary',
            name='travel_regions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='days',
            field=models.IntegerField(choices=[(3, '3-Day'), (5, '5-Day'), (7, '7-Day'), (14, '14-Day')]),
        ),
    ]
