# Generated by Django 4.2.7 on 2024-06-05 01:59

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_itinerary_covered_highlights_zh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='covered_highlights_nl',
            field=markdownx.models.MarkdownxField(default='', null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='covered_highlights_zh_cn',
            field=markdownx.models.MarkdownxField(default='', null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='details_nl',
            field=markdownx.models.MarkdownxField(default='', null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='details_zh_cn',
            field=markdownx.models.MarkdownxField(default='', null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='intro_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='intro_zh_cn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='name_nl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='name_zh_cn',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
